sim:
  initial_capital: 1000.0
  max_leverage: 20
  fee_rate: 0.0004
  slippage: 0.0

risk:
  max_position_notional: 20000.0
  max_position_pct_equity: 1.0

strategy:
  rsi_low: 30
  rsi_high: 70
  stop_loss_pct: 0.01
  rr: 1.5
  realtime_entry: false
  realtime_exit: true

indicators:
  rsi:
    length: 14
